"""initial schema

Revision ID: 4e4812ebe2a9
Revises: 
Create Date: 2026-05-26 15:51:29.861617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e4812ebe2a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibrations_clerk_user_id'), 'calibrations', ['clerk_user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='jobstatus'), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_clerk_user_id'), 'jobs', ['clerk_user_id'], unique=False)
    op.create_table('screenings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('calibration_id', sa.String(length=36), nullable=True),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calibration_id'], ['calibrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenings_clerk_user_id'), 'screenings', ['clerk_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screenings_clerk_user_id'), table_name='screenings')
    op.drop_table('screenings')
    op.drop_index(op.f('ix_jobs_clerk_user_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_calibrations_clerk_user_id'), table_name='calibrations')
    op.drop_table('calibrations')
    # ### end Alembic commands ###
